version: "3.9"

services:
  frontend:
    image: sparklemotion:latest
    container_name: sparklemotion-frontend-dev
    ports:
      - "3000:5173"
    networks:
      - sparklemotion-network-dev

  backend:
    image: sparklemotion-backend:latest
    build:
      dockerfile: Dockerfile
    container_name: sparklemotion-backend-dev
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - sparklemotion-network-dev

  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - sparklemotion-network-dev

networks:
  sparklemotion-network-dev:
    driver: bridge
